ContentEngine/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from ContentEngine import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),  # URL-Pfad zu Ihrer App
    path('', include('core.urls')),  # URL-Pfad zu Ihrer App
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls.static import static
from django.urls import path

from ContentEngine import settings
from . import views

urlpatterns = [

    path('', views.dashboard, name='dashboard'),

    path('settings/', views.settings, name='settings'),
    path('overview/', views.overview, name='overview'),

    path('ideas/', views.list_ideas, name='list_ideas'),
    path('ideas/create/', views.create_idea, name='create_idea'),
    path('ideas/<int:pk>/edit/', views.update_idea, name='update_idea'),
    path('ideas/<int:pk>/delete/', views.delete_idea, name='delete_idea'),

    path('ideas/get_ideas/', views.get_ideas, name='get_ideas'),


    path('posts/', views.list_posts, name='list_posts'),
    path('posts/<int:post_id>/', views.view_post, name='view_post'),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<int:pk>/edit/', views.update_post, name='update_post'),
    path('posts/<int:pk>/delete/', views.delete_post, name='delete_post'),

    path('posts/publish/', views.list_publish_posts, name='list_publish_posts'),
    path('posts/publications/<int:post_id>/', views.view_post_publications, name='view_post_publications'),
    path('posts/publish/youtube/<int:post_id>/', views.publish_youtube_post, name='publish_youtube_post'),
    path('posts/publish/pinterest/<int:post_id>/', views.publish_pinterest_post, name='publish_pinterest_post'),
    path('posts/publish/facebook/<int:post_id>/', views.publish_facebook_post, name='publish_facebook_post'),
    path('posts/publish/instagram/<int:post_id>/', views.publish_instagram_post, name='publish_instagram_post'),

    path('posts/<int:pk>/create_audio/', views.create_audio, name='create_audio'),
    path('posts/<int:pk>/create_article/', views.create_article, name='create_article'),
    path('posts/<int:pk>/create_seo/', views.create_seo, name='create_seo'),
    path('posts/<int:pk>/create_ig_post/', views.create_ig_post, name='create_ig_post'),
    path('posts/<int:pk>/create_ig_video/', views.create_ig_video, name='create_ig_video'),
    path('posts/<int:pk>/create_long_video/', views.create_long_video, name='create_long_video'),



    path('slides/', views.list_slides, name='list_slides'),


    path('topics/', views.list_topics, name='list_topics'),
    path('topics/create/', views.create_topic, name='create_topic'),
    path('topics/<int:pk>/edit/', views.update_topic, name='update_topic'),
    path('topics/<int:pk>/delete/', views.delete_topic, name='delete_topic'),

    path('reasons/', views.list_reasons, name='list_reasons'),
    path('reasons/create/', views.create_reason, name='create_reason'),
    path('reasons/<int:pk>/edit/', views.update_reason, name='update_reason'),
    path('reasons/<int:pk>/delete/', views.delete_reason, name='delete_reason'),

    path('projects/', views.list_projects, name='list_projects'),
    path('projects/<int:project_id>/', views.view_project, name='view_project'),
    path('project/create/', views.create_project, name='create_project'),
    path('project/<int:pk>/edit/', views.update_project, name='update_project'),
    path('project/<int:pk>/delete/', views.delete_project, name='delete_project'),

    path('accounts/', views.list_accounts, name='list_accounts'),

    path('accounts/instagram/create/', views.create_instagram_account, name='create_instagram_account'),
    path('accounts/instagram/<int:pk>/edit/', views.update_instagram_account, name='update_instagram_account'),
    path('accounts/instagram/<int:pk>/delete/', views.delete_instagram_account, name='delete_instagram_account'),


    path('accounts/facebook/create/', views.create_facebook_account, name='create_facebook_account'),
    path('accounts/facebook/<int:pk>/edit/', views.update_facebook_account, name='update_facebook_account'),
    path('accounts/facebook/<int:pk>/delete/', views.delete_facebook_account, name='delete_facebook_account'),

    path('accounts/pinterest/create/', views.create_pinterest_account, name='create_pinterest_account'),
    path('accounts/pinterest/<int:pk>/edit/', views.update_pinterest_account, name='update_pinterest_account'),
    path('accounts/pinterest/<int:pk>/delete/', views.delete_pinterest_account, name='delete_pinterest_account'),


    path('accounts/youtube/create/', views.create_youtube_account, name='create_youtube_account'),
    path('accounts/youtube/<int:pk>/edit/', views.update_youtube_account, name='update_youtube_account'),
    path('accounts/youtube/<int:pk>/delete/', views.delete_youtube_account, name='delete_youtube_account'),




    path('links/', views.list_links, name='list_links'),
    path('links/create/', views.create_link, name='create_link'),
    path('links/<int:pk>/edit/', views.update_link, name='update_link'),
    path('links/<int:pk>/delete/', views.delete_link, name='delete_link'),

]

core/models.py
from django.db import models
from django.utils.text import slugify


class SocialMedia(models.Model):
    username = models.CharField(max_length=255)
    account_link = models.CharField(max_length=511, blank=True, null=True)
    password = models.CharField(max_length=255)
    profile_image = models.ImageField(upload_to='', blank=True, null=True)

    def get_class_name(self):
        return self.__class__.__name__

    def get_update_url(self):
        class_name = self.__class__.__name__.lower()
        return f'update_{class_name}_account'

    def get_delete_url(self):
        class_name = self.__class__.__name__.lower()
        return f'delete_{class_name}_account'


class Pinterest(SocialMedia):
    access_token = models.CharField(max_length=511, null=True, blank=True)
    account_id = models.CharField(max_length=255, null=True, blank=True)

class Youtube(SocialMedia):
    access_token = models.CharField(max_length=511, null=True, blank=True)
    account_id = models.CharField(max_length=255, null=True, blank=True)

class Facebook(SocialMedia):
    access_token = models.CharField(max_length=511, null=True, blank=True)
    account_id = models.CharField(max_length=255, null=True, blank=True)


class Instagram(SocialMedia):

    access_token = models.CharField(max_length=511, null=True, blank=True)
    account_id = models.CharField(max_length=255, null=True, blank=True)


class Wordpress(SocialMedia):
    pass

class Publication(models.Model):
    datetime = models.DateTimeField()



class InstagramPublication(Publication):
    instagram_account = models.ForeignKey(Instagram, on_delete=models.CASCADE, null=True)
    pass


class FacebookPublication(Publication):
    facebook_account = models.ForeignKey(Facebook, on_delete=models.CASCADE, null=True)
    pass


class WordpressPublication(Publication):
    wordpress_account = models.ForeignKey(Wordpress, on_delete=models.CASCADE, null=True)

    pass


class YoutubePublication(Publication):
    youtube_account = models.ForeignKey(Youtube, on_delete=models.CASCADE, null=True)
    pass


class PinterestPublication(Publication):
    pinterest_account = models.ForeignKey(Pinterest, on_delete=models.CASCADE, null=True)
    pass
def project_directory_path(instance, filename):
    # Erzeugt einen Pfad im Format 'projects/{project_id}-{project_name_slug}/img/{filename}'
    project_name_slug = slugify(instance.name)
    return f'projects/{instance.id}-{project_name_slug}/img/{filename}'

class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to=project_directory_path, null=True, blank=True)
    watermark = models.ImageField(upload_to=project_directory_path, null=True, blank=True)

    slide_mask_first = models.ImageField(upload_to=project_directory_path, null=True, blank=True)
    slide_mask_regular = models.ImageField(upload_to=project_directory_path, null=True, blank=True)
    slide_mask_last = models.ImageField(upload_to=project_directory_path, null=True, blank=True)



    youtube_account = models.ForeignKey(Youtube, on_delete=models.CASCADE,blank=True, null=True)
    facebook_account = models.ForeignKey(Facebook, on_delete=models.CASCADE,blank=True, null=True)
    instagram_account = models.ForeignKey(Instagram, on_delete=models.CASCADE,blank=True, null=True)
    wordpress_account = models.ForeignKey(Wordpress, on_delete=models.CASCADE,blank=True, null=True)
    pinterest_account = models.ForeignKey(Pinterest, on_delete=models.CASCADE,blank=True, null=True)

    def instagram_publications(self):
        return InstagramPublication.objects.filter(instagram_account=self.instagram_account)

    def youtube_publications(self):
        return YoutubePublication.objects.filter(youtube_account=self.youtube_account)

    def facebook_publications(self):
        return FacebookPublication.objects.filter(facebook_account=self.facebook_account)

    def wordpress_publications(self):
        return WordpressPublication.objects.filter(wordpress_account=self.wordpress_account)

    def pinterest_publications(self):
        return PinterestPublication.objects.filter(pinterest_account=self.pinterest_account)



class Mode(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class Theme(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class Music(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='music')
    mode = models.ForeignKey(Mode ,on_delete = models.CASCADE, null=True)

    def __str__(self):
        return self.name

class BackgroundVideo(models.Model):


    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='background_video')
    theme = models.ForeignKey(Theme, on_delete = models.CASCADE, null=True)


    def __str__(self):
        return self.name

class BackgroundImage(models.Model):


    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='background_image', null=True, blank=True)
    theme = models.ForeignKey(Theme, on_delete = models.CASCADE, null=True)


    def __str__(self):
        return self.name

class Topic(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    date = models.DateField()

class Reason(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

class IGPost(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    hashtags = models.TextField()


    def get_post_category(self):
        post = Post.objects.filter(IGPost=self).first()
        return post.category if post else None

class IGSlide(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    ig_post = models.ForeignKey(IGPost, on_delete=models.CASCADE)
    number = models.IntegerField()
    png = models.ImageField()

class Video(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    videoPath = models.CharField(max_length=255)

class SpreadshirtDesign(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    pass

class Hashtag(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    name = models.TextField()
class Keyword(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    name = models.TextField()

class Article(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    title = models.CharField(max_length=255)
    intro = models.TextField(null=True)
    date = models.DateField(null=True)
    subtitle_1 = models.TextField(null=True)
    text_1 = models.TextField(null=True)
    subtitle_2 = models.TextField(null=True)
    text_2 = models.TextField(null=True)
    subtitle_3 = models.TextField(null=True)
    text_3 = models.TextField(null=True)
    cta_title = models.TextField(null=True)
    cta_text = models.TextField(null=True)
class AudioComment(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    audio = models.FileField()
    skript = models.TextField()

class LongVideo(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    videoPath = models.CharField(max_length=255)
    audio = models.ForeignKey(AudioComment, on_delete=models.CASCADE)

class PostType(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)


class Post(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    post_type = models.CharField(max_length=255, null=True, blank=True)
    POST_TYPE_CHOICES = [
        ('1', 'Instagram Image'),
        ('2', 'Instagram Video'),
        ('3', 'Instagram Slider'),
    ]
    mode = models.ForeignKey(Mode, on_delete=models.CASCADE, null=True, blank=True)

    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    IGPost = models.ForeignKey(IGPost, on_delete=models.CASCADE, null=True)
    Video = models.ForeignKey(Video, on_delete=models.CASCADE, null=True)
    audio = models.ForeignKey(AudioComment, on_delete=models.CASCADE, null=True)
    LongVideo = models.ForeignKey(LongVideo, on_delete=models.CASCADE, null=True)

    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)  # Many-to-Many-Beziehung zu Hashtag
    keywords = models.ManyToManyField(Keyword, blank=True)  # Many-to-Many-Beziehung zu Hashtag
    meta = models.TextField(null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)

    instagram_publication = models.ForeignKey(InstagramPublication, on_delete=models.CASCADE, null=True)
    facebook_publication = models.ForeignKey(FacebookPublication, on_delete=models.CASCADE, null=True)
    pinterest_publication = models.ForeignKey(PinterestPublication, on_delete=models.CASCADE, null=True)
    youtube_publication = models.ForeignKey(YoutubePublication, on_delete=models.CASCADE, null=True)
    wordpress_publication = models.ForeignKey(WordpressPublication, on_delete=models.CASCADE, null=True)



    def get_full_content(self):
        content = f"Topic: {self.topic.name}\nDescription: {self.topic.description}\n\nReasons:\n"
        reasons = Reason.objects.filter(topic=self.topic)

        for reason in reasons:
            content += f"- {reason.name}: {reason.description}\n"

        # Hinzufügen der Hashtags zum Inhalt

core/templates/core/account_instagram_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p class="card-text">Sind Sie sicher, dass Sie "{{ object.name }}" löschen möchten?</p>
                <button type="submit" class="btn btn-danger">Löschen</button>
                <a href="{% url 'list_accounts' %}" class="btn btn-secondary">Abbrechen</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/account_instagram_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-3">
            <label for="id_user_name" class="form-label">Instagram Username:</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="id_account_id" class="form-label">Instagram Account ID:</label>
            {{ form.account_id }}
        </div>
        <div class="mb-3">
            <label for="id_access_token" class="form-label">Access Token:</label>
            {{ form.access_token }}
        </div>
            <div class="mb-3">
            <label for="id_image" class="form-label">Bild:</label>
            {{ form.profile_image }}
        </div>
        <!-- Weitere Felder mit entsprechenden Labels und Bootstrap-Klassen -->
        <button type="submit" class="btn btn-primary">Projekt erstellen</button>
    </form>
</div>
{% endblock %}

core/templates/core/idea_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Sind Sie sicher, dass Sie "{{ object }}" löschen möchten?</p>
    <button type="submit">Löschen</button>
    <a href="{% url 'list_ideas' %}">Abbrechen</a>
</form>
{% endblock %}

core/templates/core/post_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
<form method="post">
    {% csrf_token %}

    <div class="mb-3">
        <label for="idea_selector" class="form-label">Idee auswählen:</label>
        <select id="idea_selector" name="idea_selector" class="form-control">
            {% for idea in ideas %}
                <option value="{{ idea.id }}">{{ idea.idea }}</option>
            {% endfor %}
        </select>
    </div>
 <div class="mb-3">
        <label for="type_selector" class="form-label">Beitrags Typ auswählen:</label>
        <select id="type_selector" name="type_selector" class="form-control">
            {% for type in post_types %}
                <option value="{{ type.id }}">{{ type.name }}</option>
            {% endfor %}
        </select>
    </div>
  <div class="mb-3">
        <label for="project_selector" class="form-label">Projekt auswählen:</label>
        <select id="project_selector" name="project_selector" class="form-control">
            {% for project in projects %}
                <option value="{{ project.id }}">{{ project.name }}</option>
            {% endfor %}
        </select>
    </div>
  <!-- Dropdown für Category -->
    <div class="mb-3">
        <label for="category_selector" class="form-label">Kategorie auswählen:</label>
        <select id="category_selector" name="category" class="form-control">
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
    </div>
  <!-- Dropdown für Idee -->
    <div class="mb-3">
        <label for="mode_selector" class="form-label">Stimmung auswählen:</label>
        <select id="mode_selector" name="mode" class="form-control">
            {% for mode in modes %}
                <option value="{{ mode.id }}">{{ mode.name }}</option>
            {% endfor %}
        </select>
    </div>
    <!-- Dropdown für Theme -->
    <div class="mb-3">
        <label for="theme_selector" class="form-label">Theme auswählen:</label>
        <select id="theme_selector" name="theme" class="form-control">
            {% for theme in themes %}
                <option value="{{ theme.id }}">{{ theme.name }}</option>
            {% endfor %}
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Generate Post</button>
</form>
    </div>
{% endblock %}

core/templates/core/post_publications_view.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card">
            <h1>Beitrag: {{ post.topic.name }}</h1>
            <p>{{ post.topic.description }}</p>
        </div>
        <div class="card">
            <h3>Youtube:</h3>
        </div>
        <div class="card">
            <h3>Pinterest:</h3>
        </div>
         <div class="card">
            <h3>Facebook:</h3>
        </div>
        <div class="card">
            <h3>Instagram:</h3>
        </div>
    </div>
</div>



{% endblock %}

core/templates/core/post_view.html
{% extends 'base.html' %}
{%  load static %}

{% block content %}
<div class="container mt-4">
<div class="card">
<div class="card">
    <h1>Beitrag: {{ post.topic.name }}</h1>
    <p>{{ post.topic.description }}</p>

    <!-- Liste der Gründe mit Bootstrap-Styling -->
    <ul class="list-group mb-4">
        {% for reason in reasons %}
            <li class="list-group-item">
                <strong>{{ reason.name }}</strong> - {{ reason.description }}
            </li>
        {% endfor %}
    </ul>
</div>
<div class="card">
    <h5>Publikationen:</h5>
        <div class="col-12 mb-3 mb-lg-5">
            <div class="card table-nowrap table-card">
                <div class="table-responsive">
                    <table class="table mb-0">
                        <tbody>
                            <tr class="align-middle">
                                <td>
                                    <img src="{% static 'core/instagram_published.png' %}" alt="SEO" class="icon-40px">
                                </td>
                                <td class="font-size-12">
                                   <h6>Instagram:</h6>
                                </td>
                                <td class="font-size-12">
                                    {% if post.instagram_publications %}
                                        {{ post.instagram_publications.datetime }}
                                    {% else %}
                                        Noch nicht veröffentlicht
                                    {% endif %}
                                </td>
                            </tr>
                            <tr class="align-middle">
                             <td>
                                    <img src="{% static 'core/facebook_published.png' %}" alt="SEO" class="icon-40px">
                                </td>
                                <td class="font-size-12">
                                   <h6>Facebook:</h6>
                                </td>
                                <td class="font-size-12">
                                    {% if post.facebook_publications %}
                                        {{ post.facebook_publications.datetime }}
                                    {% else %}
                                        Noch nicht veröffentlicht
                                    {% endif %}
                                </td>
                            </tr>
                            <tr class="align-middle">
                             <td>
                                    <img src="{% static 'core/pinterest_published.png' %}" alt="SEO" class="icon-40px">
                                </td>
                                <td class="font-size-12">
                                   <h6>Pinterest:</h6>
                                </td>
                                <td class="font-size-12">
                                    {% if post.pinterest_publications %}
                                        {{ post.pinterest_publications.datetime }}
                                    {% else %}
                                         Noch nicht veröffentlicht
                                    {% endif %}
                                </td>
                            </tr>
                            <tr class="align-middle">
                             <td>
                                    <img src="{% static 'core/youtube_published.png' %}" alt="SEO" class="icon-40px">
                                </td>
                                <td class="font-size-12">
                                   <h6>Youtube:</h6>
                                </td>
                                <td class="font-size-12">
                                    {% if post.youtube_publications %}
                                        {{ post.youtube_publications.datetime }}
                                    {% else %}
                                           Noch nicht veröffentlicht
                                    {% endif %}
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<div class="card">
    <!-- Anzeige der Hashtags -->
    {% if post.hashtags.all %}
        <h3>Hashtags:</h3>
        <p>
            {% for hashtag in post.hashtags.all %}
                <span class="badge bg-secondary">{{ hashtag.name }}</span>
            {% endfor %}
        </p>
        <h3>Keywords:</h3>
        <p>
            {% for keyword in post.keywords.all %}
                <span class="badge bg-secondary">{{ keyword.name }}</span>
            {% endfor %}
        </p>
             <h3>Meta:</h3>
        <p>

            <p>{{ post.meta }}</p>

        </p>



    {% endif %}
 </div>
<div class="card">
 <h2>Video & Images:</h2>
    <div class="row">
        <!-- Instagram Post Slider -->
        <div class="col-md-6">
            <div id="igSlider" class="mb-4">
                {% for slide in ig_slides %}
                    <div>
                        <img src="{{ slide.png.url }}" class="img-fluid" alt="Slide {{ forloop.counter }}">
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- Video Player -->
        <div class="col-md-6">
            {% if post.Video %}
                <video controls class="img-fluid">
                    <source src="{{ MEDIA_URL }}{{ post.Video.videoPath }}" type="video/mp4">
                    Ihr Browser unterstützt kein Video.
                </video>
            {% endif %}
        </div>
    </div>
 </div>
<div class="card">
{% if post.article %}
    <h2>Article:</h2>

    <div>
        <h5>{{ post.article.title }}</h5>
        <p>{{ post.article.intro|linebreaks }}</p>

        {% if post.article.subtitle_1 %}
            <h5>{{ post.article.subtitle_1 }}</h5>
            <p>{{ post.article.text_1|linebreaks }}</p>
        {% endif %}

        {% if post.article.subtitle_2 %}
            <h5>{{ post.article.subtitle_2 }}</h5>
            <p>{{ post.article.text_2|linebreaks }}</p>
        {% endif %}

        {% if post.article.subtitle_3 %}
            <h5>{{ post.article.subtitle_3 }}</h5>
            <p>{{ post.article.text_3|linebreaks }}</p>
        {% endif %}

        {% if post.article.cta_title %}
            <h5>{{ post.article.cta_title }}</h5>
            <p>{{ post.article.cta_text|linebreaks }}</p>
        {% endif %}
    </div>
{% endif %}
 </div>

    <!-- Bearbeitungsformulare für Topic und Reasons -->
    <!-- Ihre bestehenden Formulare -->
</div>
    </div>
{% endblock %}

core/templates/core/slide_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
    <script>
$(document).ready(function(){
    $('.slick-slider').slick({
        dots: true,
        infinite: true,
        speed: 300,
        slidesToShow: 1,
        adaptiveHeight: true
    });
});
</script>


<div class="container">
    <div class="card">
        <div class="card">
            <div class="row">
                <div class="col-md-2">
                    <img src="{% static 'core/post.png' %}" alt="Post Icon" style="height: 64px; width: 64px; margin-right: 10px;">
                </div>
                <div class="col-md-6">
                    <h2>Beiträge</h2>
                </div>
                <div class="col-md-4">
                    <a class="btn btn-success" href="{% url 'create_post' %}">Beitrag aus Idee erstellen</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="row">
                <form method="get" action="{% url 'list_posts' %}" class="mb-3">
                    <div class="row">
                        <div class="col-md-4">
                            <select name="category" class="form-control">
                                <option value="">Alle Kategorien</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-4">
                            <select name="sort" class="form-control">
                                <option value="datetime_asc">Datum aufsteigend</option>
                                <option value="datetime_desc">Datum absteigend</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-primary">Filtern und sortieren</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>


    <div class="row">
        {% for ig_post in ig_posts %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div id="igSlider-{{ ig_post.id }}" class="slick-slider">
                    {% for slide in ig_post.igslide_set.all %}
                    <div>
                        <img src="{{ slide.png.url }}" class="d-block w-100" alt="Slide {{ forloop.counter }}">
                    </div>
                    {% endfor %}
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                             <span class="badge bg-secondary">{{ ig_post.get_post_category }}</span>


                        </div>
                            <div class="col-md-6">
                             <span class="badge bg-secondary">{{ ig_post.datetime}}</span>


                        </div>

                    </div>

                    <h6 class="card-title">{{ ig_post.title }}</h6>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>


    <!-- Pagination usw. -->

<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% for num in posts.paginator.page_range %}
            {% if posts.number == num %}
                <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
</div>
           </div>



{% endblock %}